apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
     grafana_datasource: "1"
data:  
  datasources.yaml: |-
    # config file version
    apiVersion: 1
    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: Graphite
        orgId: 1
    # datasources to be added
    datasources:
    - name: AzureMonitor
      type: grafana-azure-monitor-datasource
      isDefault: true
      access: proxy
      jsonData:
        cloudName: azuremonitor
        azureLogAnalyticsSameAs: false
        subscriptionId: $SUBSCRIPTIONID
        tenantId: $TENANTID
        clientId: $CLIENTID
        logAnalyticsSubscriptionId: $SUBSCRIPTIONID
        logAnalyticsTenantId: $TENANTID
        logAnalyticsClientId: $CLIENTID
        logAnalyticsDefaultWorkspace: $WORKSPACE
      secureJsonData:
        clientSecret: $CLIENTSECRET
        logAnalyticsClientSecret: $CLIENTSECRET
      version: 1